# Utility to store all kind of ResponseCodes generated by
# service layer
module CommonModule
  class ResponseCodes < BaseModule::BaseUtil
    SUCCESS = "Operation successfull"
    NO_CONTENT = "No need to send any content"
    BAD_REQUEST = "Request could not be understood due to malformed data"
    UN_AUTHORIZED = "Request requires user authentication"
    FORBIDDEN = "User doesn't have enough permissions for this request"
    NOT_FOUND = "Requested entity can not found"
    AUTHENTICATION_TIMEOUT = "Authentication request has expired"
    UNPROCESSABLE_ENTITY = "Request can not be processed"
    PRE_CONDITION_REQUIRED = "You are still in Inactive state"
    TOO_MANY_REQUESTS = "You have reached the maximum limit"
    INTERNAL_SERVER_ERROR = "Internal server error occurred"
    PRE_CONDITION_FAILED = "Pre Condition Failed"
    CONFLICT_IN_STATE = 'Conflict in resource state'
  end
end
